version: '3'
services: 
    mariadb:
        image: mariadb:latest
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - ./mysql-dump/:/docker-entrypoint-initdb.d/
